name: Build TwoYi

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust and Cargo
        run: |
          sudo apt-get update
          sudo apt-get install -y curl build-essential
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env

      - name: Build project
        run: cargo build --release
